# Generated by Django 3.2.5 on 2021-07-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.TextField(max_length=32, verbose_name='出版社'),
        ),
    ]
