# Generated by Django 3.2.5 on 2021-07-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_goods_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/detail/', verbose_name='图片'),
        ),
    ]
