# Generated by Django 3.2.5 on 2021-07-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='userfav',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='userleavingmessage',
            old_name='add_time',
            new_name='create_time',
        ),
    ]
