# Generated by Django 3.2.5 on 2021-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20210729_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(help_text='上传的文件', null=True, upload_to='message/images/', verbose_name='上传的文件'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='message',
            field=models.CharField(help_text='留言内容', max_length=800, verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='主题'),
        ),
    ]
