# Generated by Django 3.2.5 on 2021-08-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20210801_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userleavingmessage',
            name='file',
        ),
        migrations.AddField(
            model_name='userleavingmessage',
            name='image',
            field=models.ImageField(help_text='上传图片', null=True, upload_to='message/images/', verbose_name='上传的图片'),
        ),
    ]
