# Generated by Django 3.2.5 on 2021-07-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='updated_time',
            new_name='update_time',
        ),
    ]
