# Generated by Django 3.2.5 on 2021-07-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_remove_orderinfo_nonce_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='subject',
            field=models.CharField(max_length=150, null=True, verbose_name='订单标题'),
        ),
    ]
