# Generated by Django 3.2.5 on 2021-08-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_orderinfo_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='update_time',
        ),
    ]
