# Generated by Django 3.2.5 on 2021-08-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_remove_orderinfo_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='post_script',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='订单留言'),
        ),
    ]
