# Generated by Django 3.2.5 on 2021-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20210801_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='订单标题'),
        ),
    ]
